#cloud-config
install:
  image: "docker:quay.io/unconventionalmindset/kairos-fedora-transcoding:2.0.1-kairos-3.5.2-k3s-1.33.4"
  device: "/dev/vda"
  auto: true
  reboot: true

debug: true

hostname: kairos-fed-k3s-e2
users:
- name: kairos
  groups:
    - "admin"
  ssh_authorized_keys:
    - "github:UnconventionalMindset"
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCoPJQAHkfSRIfS05ptesdKwTX7ererHcTZ7pKWi7yUqOQv1e2xpfNBcfx/trwzITJe9N7bwp7t6gpPY2/yBr8F6TenigFWhDaF3Qi9kdSlv64eOsPv6iTg0URH7RE4RQwdArPuwAEBA79BOVoJ0qG/zgn0LOlqYGE/EameYxtgzDJNjXPWOi6OkPKhOEc00+wWGucsCw/8a6rzaMbQHn647yiS7XUJ9/QgMwZ5tqT+Fw/1dxzV4zrWK5MVEXlN5wRZEzukadPQJKyZhhhx3o7MqEVOsTHvyBln6NVJGFawQY7B+ffN/+9n6pEuskWCqngywqAvDXyRS7zD/Dxqv5pjzSQI2fkyuM21oRcKlSYx2AB4L46J6MRJ4ZLA5dhY0fwv868F5VFmJZ2AsDmaGFCqdXTMCv6VRnghJo75oybv+/eoV53NETrTeB4XsPOxSZOHmK93zJzGw2hT4X/ZTvyVbnCyU+Z4sg2iU8ZVE3pHJi8ZQ3hadW0N+CAAmVQ+zsE= nousername"

k3s:
  enabled: true
  args:
  - --disable=traefik,servicelb
  - --node-ip 192.168.31.192
  - --server https://192.168.31.193:6443
  - --cni-bin-dir=/var/lib/rancher/k3s/data/current/bin
  # Token will be generated if not specified at /var/lib/rancher/k3s/server/node-token
  env:
    K3S_NODE_NAME: "e2"
    K3S_TOKEN: ""

stages:
    boot:
      - systemctl:
          disable:
            - firewalld
    initramfs:
        - files:
            - content: |
                [connection]
                id=wired-fixed-ip
                type=802-3-ethernet
                autoconnect=true
                interface-name=ens18
                autoconnect-priority=10

                [ethernet]

                [ipv4]
                method=manual
                addresses=192.168.31.192/24
                gateway=192.168.31.1
                dns=1.1.1.1;8.8.8.8
                dns-search=
              path: /etc/NetworkManager/system-connections/static-ethernet.nmconnection
              permissions: 0600
              owner: 0
              group: 0

#    # "boot" is the stage
#    boot:
#      - systemd_firstboot:
#          keymap: uk
#      - modules:
#        - nvidia
#        authorized_keys:
#          kairos
#         - "github:UnconventionalMindset"
#         - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCoPJQAHkfSRIfS05ptesdKwTX7ererHcTZ7pKWi7yUqOQv1e2xpfNBcfx/trwzITJe9N7bwp7t6gpPY2/yBr8F6TenigFWhDaF3Qi9kdSlv64eOsPv6iTg0URH7RE4RQwdArPuwAEBA79BOVoJ0qG/zgn0LOlqYGE/EameYxtgzDJNjXPWOi6OkPKhOEc00+wWGucsCw/8a6rzaMbQHn647yiS7XUJ9/QgMwZ5tqT+Fw/1dxzV4zrWK5MVEXlN5wRZEzukadPQJKyZhhhx3o7MqEVOsTHvyBln6NVJGFawQY7B+ffN/+9n6pEuskWCqngywqAvDXyRS7zD/Dxqv5pjzSQI2fkyuM21oRcKlSYx2AB4L46J6MRJ4ZLA5dhY0fwv868F5VFmJZ2AsDmaGFCqdXTMCv6VRnghJo75oybv+/eoV53NETrTeB4XsPOxSZOHmK93zJzGw2hT4X/ZTvyVbnCyU+Z4sg2iU8ZVE3pHJi8ZQ3hadW0N+CAAmVQ+zsE= nousername"

